(function(){
  'use strict';
  const R=window.StepProgressSync,C=R.config,U=R.util,S=R.storage,A=R.auth,B=R.backupModel;
  let running=null,checkpointTimer=null,cloudState={manifest:null,file:null,files:[]},decisionKeys=[];
  let uiState={status:'Disconnected',detail:'Progress is stored locally in this isolated TEST build.',lastBackup:'',lastError:'',account:'',summary:null};
  const emit=()=>{try{window.dispatchEvent(new CustomEvent('stepsync:state',{detail:{...uiState}}));}catch(e){}renderUi();};
  function setStatus(status,detail='',extra={}){uiState={...uiState,status,detail,...extra};emit();}
  const getMap=async(k)=>await R.meta.get(k,{})||{};
  const setMap=(k,v)=>R.meta.set(k,v||{});
  async function markDirtyKey(key,reason){if(window.__STEP_SYNC_APPLYING_REMOTE)return;const d=await getMap('dirtyKeys');d[key]={at:U.iso(),reason:reason||'progress changed'};await setMap('dirtyKeys',d);setStatus(navigator.onLine===false?'Offline — saved locally':'Local backup pending',reason||'Progress changed locally.');}
  async function markDirtyAll(reason){await R.meta.set('dirtyAll',{at:U.iso(),reason:reason||'progress metadata changed'});setStatus(navigator.onLine===false?'Offline — saved locally':'Local backup pending',reason||'Progress changed locally.');}
  async function keyForProgressFilename(name){
    if(/^QBANK_MODE_progress\.json$/i.test(name))return B.qbankKey;
    const m=String(name||'').match(/^(.+?)_(?:progress_save|suspended_test)\.json$/i);if(!m)return'';
    try{const cat=await window.StepExamSyncBridge.catalog(),rec=(cat.forms||[]).find(x=>String(x.id)===m[1]);return rec?B.entityKey(rec.id,rec.bankHash):'';}catch(e){return'';}
  }
  async function recordProgressMutation(detail){
    if(window.__STEP_SYNC_APPLYING_REMOTE)return;
    const key=await keyForProgressFilename(detail?.filename);if(!key)return;
    await markDirtyKey(key,`${detail?.filename||'progress'} ${detail?.operation||'changed'}`);
    if(String(detail?.operation||'')==='delete'){const p=await getMap('protectedDeletes');p[key]={at:U.iso()};await setMap('protectedDeletes',p);}
  }
  function scheduleCheckpoint(reason,delay=1800){clearTimeout(checkpointTimer);checkpointTimer=setTimeout(()=>backupNow({reason,interactive:false}).catch(()=>{}),delay);}
  function escapeQ(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'");}
  async function listByName(name){
    const q=`name = '${escapeQ(name)}' and trashed = false`,params=new URLSearchParams({spaces:'appDataFolder',q,fields:'files(id,name,modifiedTime,size)',orderBy:'modifiedTime desc',pageSize:'20'});
    const r=await A.driveFetch('https://www.googleapis.com/drive/v3/files?'+params.toString());const d=await r.json();return Array.isArray(d.files)?d.files:[];
  }
  async function downloadJson(id,label){const r=await A.driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`);return U.parseJson(await r.text(),label);}
  async function createFile(name){const r=await A.driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name,modifiedTime',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,parents:['appDataFolder'],mimeType:'application/json'})});return await r.json();}
  async function uploadJson(id,obj){const r=await A.driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(id)}?uploadType=media&fields=id,name,modifiedTime,size`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});return await r.json();}
  async function removeDuplicateFiles(files,keep){for(const f of files||[]){if(f.id===keep)continue;try{await A.driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(f.id)}`,{method:'DELETE'});}catch(e){console.warn('Could not remove duplicate TEST backup metadata file',e);}}}
  function emptyManifest(deviceId=''){return {type:C.MANIFEST_TYPE,schemaVersion:C.SCHEMA_VERSION,updatedAt:U.iso(),build:C.BUILD,lastWriterDeviceId:deviceId,entries:{}};}
  function validateManifest(m){if(!m||typeof m!=='object'||m.type!==C.MANIFEST_TYPE)throw new Error('Cloud manifest is invalid.');if(Number(m.schemaVersion)!==C.SCHEMA_VERSION)throw new Error(`Unsupported cloud manifest schema ${String(m.schemaVersion)}.`);if(!m.entries||typeof m.entries!=='object'||Array.isArray(m.entries))m.entries={};return m;}
  async function readManifest(){
    const files=await listByName(C.MANIFEST_FILE);if(!files.length){cloudState={manifest:null,file:null,files:[]};return cloudState;}
    const file=files[0],manifest=validateManifest(await downloadJson(file.id,'Google Drive backup manifest'));cloudState={manifest,file,files};return cloudState;
  }
  async function writeManifest(manifest){
    manifest.updatedAt=U.iso();manifest.build=C.BUILD;manifest.lastWriterDeviceId=await R.meta.deviceId();let file=cloudState.file;
    if(!file)file=await createFile(C.MANIFEST_FILE);const up=await uploadJson(file.id,manifest);await removeDuplicateFiles(cloudState.files||[],file.id);cloudState={manifest,file:{...file,...up},files:[{...file,...up}]};return up;
  }
  function fileNameFor(entity){if(entity.kind==='qbank')return 'QBANK.progress.backup.json';return `FORM_${U.safeName(entity.formId)}_${U.safeName(String(entity.bankHash||'').slice(0,12))}.progress.backup.json`;}
  async function ensureBackupFile(entity,remoteEntry){
    if(remoteEntry?.fileId)return {id:remoteEntry.fileId,name:remoteEntry.fileName||fileNameFor(entity)};
    const name=remoteEntry?.fileName||fileNameFor(entity),found=await listByName(name);if(found.length)return found[0];return await createFile(name);
  }
  async function uploadEntity(entity,manifest,{force=false}={}){
    const key=entity.key,remote=manifest.entries[key]||null,known=await getMap('knownCloud'),lastHashes=await getMap('lastBackedUpHash'),protectedDeletes=await getMap('protectedDeletes');
    if(!force&&remote&&protectedDeletes[key]&&entity.contentHash!==remote.contentHash)return {conflict:true,key,entity,remote,reason:'local progress was reset/deleted after the last backup'};
    if(!force&&remote){const knownId=known[key]?.backupId||'';if(!knownId||knownId!==remote.backupId){if(entity.contentHash!==remote.contentHash)return {conflict:true,key,entity,remote};}}
    if(remote&&entity.contentHash===remote.contentHash){known[key]={backupId:remote.backupId,contentHash:remote.contentHash};lastHashes[key]=entity.contentHash;await setMap('knownCloud',known);await setMap('lastBackedUpHash',lastHashes);return {unchanged:true,key};}
    const deviceId=await R.meta.deviceId(),meta={backupId:U.uuid(),revision:Number(remote?.revision||0)+1,updatedAt:U.iso(),deviceId,contentHash:entity.contentHash};
    const backup=entity.kind==='qbank'?S.makeQbankBackup(entity,meta):S.makeFormBackup(entity,meta),file=await ensureBackupFile(entity,remote),uploaded=await uploadJson(file.id,backup);
    manifest.entries[key]={key,kind:entity.kind,formId:entity.formId||'',bankHash:entity.bankHash||'',fileId:file.id,fileName:file.name||fileNameFor(entity),backupId:meta.backupId,revision:meta.revision,contentHash:meta.contentHash,updatedAt:uploaded.modifiedTime||meta.updatedAt,deviceId,size:Number(uploaded.size||new Blob([JSON.stringify(backup)]).size)};
    known[key]={backupId:meta.backupId,contentHash:meta.contentHash};lastHashes[key]=entity.contentHash;await setMap('knownCloud',known);await setMap('lastBackedUpHash',lastHashes);
    const p=await getMap('protectedDeletes');delete p[key];await setMap('protectedDeletes',p);
    return {uploaded:true,key,entry:manifest.entries[key]};
  }
  async function analyze({flush=false}={}){
    const local=await S.localIndex({flush}),cs=await readManifest(),manifest=cs.manifest||emptyManifest(local.deviceId),known=await getMap('knownCloud'),lastHashes=await getMap('lastBackedUpHash'),dirty=await getMap('dirtyKeys'),dirtyAll=await R.meta.get('dirtyAll',null),protectedDeletes=await getMap('protectedDeletes');
    const rows=[],keys=new Set([...Object.keys(local.index),...Object.keys(manifest.entries||{})]);let conflicts=0,pending=0,cloudNewer=0,cloudOnly=0,aligned=0;
    for(const key of [...keys].sort()){
      const l=local.index[key]||null,r=manifest.entries[key]||null,k=known[key]||null,localChanged=!!l&&(dirtyAll||dirty[key]||!lastHashes[key]||lastHashes[key]!==l.contentHash),remoteChanged=!!r&&(!k||k.backupId!==r.backupId),same=!!l&&!!r&&l.contentHash===r.contentHash;
      let state='';if(same){state='aligned';aligned++;}else if(l&&r&&protectedDeletes[key]){state='conflict';conflicts++;}else if(l&&r&&localChanged&&remoteChanged){state='conflict';conflicts++;}else if(l&&localChanged){state='local-pending';pending++;}else if(r&&remoteChanged){state='cloud-newer';cloudNewer++;}else if(!l&&r){state='cloud-only';cloudOnly++;}else if(l&&!r){state='local-pending';pending++;}else state='aligned';
      if(protectedDeletes[key]&&r&&!l)state='cloud-only';
      rows.push({key,local:l,remote:r,known:k,state,localChanged,remoteChanged});
    }
    const summary={localCount:Object.keys(local.index).length,cloudCount:Object.keys(manifest.entries||{}).length,conflicts,pending,cloudNewer,cloudOnly,aligned,manifestUpdatedAt:cs.manifest?.updatedAt||'',rows};
    return {local,manifest,summary};
  }
  function setAnalysisStatus(a){
    uiState.summary=a.summary;decisionKeys=a.summary.rows.filter(r=>r.state==='conflict').map(r=>r.key);
    if(a.summary.conflicts)setStatus('Backup decision required',`${a.summary.conflicts} progress file${a.summary.conflicts===1?'':'s'} changed both locally and in cloud. Nothing was overwritten.`,{summary:a.summary});
    else if(a.summary.cloudNewer||a.summary.cloudOnly)setStatus('Cloud backup available',`${a.summary.cloudNewer+a.summary.cloudOnly} cloud backup${a.summary.cloudNewer+a.summary.cloudOnly===1?'':'s'} differ from this device. Use Restore from Cloud if you want them.`,{summary:a.summary});
    else if(a.summary.pending)setStatus('Local backup pending',`${a.summary.pending} local progress file${a.summary.pending===1?'':'s'} can be backed up.`,{summary:a.summary});
    else setStatus('Backed up','Local progress and the known cloud backup lineage are aligned.',{summary:a.summary});
  }
  async function checkCloud({interactive=false}={}){
    if(navigator.onLine===false){setStatus('Offline — saved locally','Cloud manifest cannot be checked while offline. Local progress is safe.');return null;}
    if(!A.getState().authorized){if(interactive){const acct=await A.connect({forceConsent:false});uiState.account=acct.emailAddress||'';await R.meta.set('syncEnabled',true);}else{setStatus('Reconnect Google','Cloud backup is enabled, but Google authorization is not available in this browser session.');return null;}}
    const acct=await A.validate();uiState.account=acct.emailAddress||'';const a=await analyze({flush:false});setAnalysisStatus(a);return a;
  }
  async function backupCore({reason='manual',interactive=false,force=false}={}){
    const enabled=await R.meta.get('syncEnabled',false);if(!enabled&&!interactive){setStatus('Disconnected','Google backup is disabled on this device.');return null;}
    if(navigator.onLine===false){setStatus('Offline — saved locally','Backup pending. Local progress is safe.');return null;}
    if(!A.getState().authorized){if(!interactive){setStatus('Reconnect Google','Google authorization is required before backup.');return null;}const acct=await A.connect({forceConsent:false});uiState.account=acct.emailAddress||'';await R.meta.set('syncEnabled',true);}
    const acct=await A.validate();uiState.account=acct.emailAddress||'';setStatus('Backing up…',reason);
    const a=await analyze({flush:true}),manifest=a.manifest;const dirty=await getMap('dirtyKeys'),dirtyAll=await R.meta.get('dirtyAll',null),lastHashes=await getMap('lastBackedUpHash');
    const candidates=[];for(const row of a.summary.rows){if(!row.local)continue;const changed=!!(dirtyAll||dirty[row.key]||!lastHashes[row.key]||lastHashes[row.key]!==row.local.contentHash);if(changed)candidates.push(row.local);}
    if(!candidates.length){setAnalysisStatus(a);return {uploaded:0,conflicts:[]};}
    const conflicts=[],done=[];for(const ent of candidates){const r=await uploadEntity(ent,manifest,{force});if(r.conflict)conflicts.push(r);else done.push(r);}
    if(done.some(x=>x.uploaded))await writeManifest(manifest);
    const dirtyNext=await getMap('dirtyKeys');for(const x of done)delete dirtyNext[x.key];await setMap('dirtyKeys',dirtyNext);if(dirtyAll)await R.meta.del('dirtyAll');
    if(done.some(x=>x.uploaded)){const t=cloudState.file?.modifiedTime||U.iso();await R.meta.set('lastBackupAt',t);uiState.lastBackup=t;}
    const after=await analyze({flush:false});if(conflicts.length){decisionKeys=conflicts.map(x=>x.key);setStatus('Backup decision required',`${conflicts.length} cloud backup${conflicts.length===1?'':'s'} changed since this device last knew them. Safe files were backed up; conflicting files were left untouched.`,{summary:after.summary});}else setAnalysisStatus(after);
    return {uploaded:done.filter(x=>x.uploaded).length,conflicts};
  }
  async function backupNow(opts={}){if(running)return running;running=backupCore(opts).catch(async e=>{await handleError(e);throw e;}).finally(()=>{running=null;});return running;}
  async function forceBackup(){
    if(!confirm('Replace conflicting cloud backups with the progress currently on THIS DEVICE? Cloud-only backups with no local copy will be preserved.'))return;
    await backupNow({reason:'Explicit Replace Cloud with This Device',interactive:true,force:true});
  }
  async function restoreFromCloud(){
    const rt=window.StepExamSyncBridge?.runtime?.();if(rt?.examVisible)throw new Error('Leave the active exam before restoring cloud progress.');
    if(!A.getState().authorized){const acct=await A.connect({forceConsent:false});uiState.account=acct.emailAddress||'';await R.meta.set('syncEnabled',true);}
    const a=await analyze({flush:true}),entries=Object.values(a.manifest.entries||{});if(!entries.length){setStatus('Backed up','No cloud backups exist yet.');return;}
    const loadedKeys=new Set(Object.keys(a.local.forms||{}));const catalogKeys=new Set((a.local.catalog.forms||[]).map(r=>B.entityKey(r.id,r.bankHash)));const restorable=entries.filter(e=>e.kind==='qbank'||catalogKeys.has(e.key));const skipped=entries.length-restorable.length;
    if(!restorable.length)throw new Error('Cloud backups exist, but none match forms currently loaded on this device. Import the matching forms first.');
    if(!confirm(`Restore ${restorable.length} matching cloud backup${restorable.length===1?'':'s'} to this device? Existing local progress for those items will be replaced. A local recovery checkpoint will be created first.${skipped?` ${skipped} unmatched backup(s) will be left untouched.`:''}`))return;
    await S.checkpoint();const known=await getMap('knownCloud'),lastHashes=await getMap('lastBackedUpHash'),dirty=await getMap('dirtyKeys');let restored=0;
    try{
      for(const entry of restorable){const obj=S.validateBackup(await downloadJson(entry.fileId,entry.fileName||entry.key),entry);await S.applyBackup(entry,obj);known[entry.key]={backupId:entry.backupId,contentHash:entry.contentHash};lastHashes[entry.key]=entry.contentHash;delete dirty[entry.key];restored++;}
    }catch(e){try{await S.restoreCheckpoint();}catch(rb){console.error('Cloud restore rollback failed',rb);}throw new Error(`Cloud restore failed; the pre-restore local checkpoint was reapplied. ${e.message}`);}
    await setMap('knownCloud',known);await setMap('lastBackedUpHash',lastHashes);await setMap('dirtyKeys',dirty);await R.meta.del('dirtyAll');const p=await getMap('protectedDeletes');for(const e of restorable)delete p[e.key];await setMap('protectedDeletes',p);
    const after=await analyze({flush:false});setStatus('Backed up',`Restored ${restored} cloud backup${restored===1?'':'s'} to this device.`,{summary:after.summary});await runValidate();
  }
  async function connect(){
    setStatus('Connecting…','Connecting Google account…');try{const acct=await A.connect({forceConsent:false});await R.meta.set('syncEnabled',true);uiState.account=acct.emailAddress||'';const a=await analyze({flush:false});setAnalysisStatus(a);}catch(e){await handleError(e);throw e;}
  }
  async function disconnect(){A.disconnect();await R.meta.set('syncEnabled',false);setStatus('Disconnected','Google backup is disabled on this browser. Local progress and existing cloud backup files remain untouched.',{account:'',lastError:''});}
  async function handleError(e){console.error('Progress backup failed',e);await R.meta.set('lastError',{at:U.iso(),message:e.message||String(e),status:e.status||0,reason:e.reason||''});if(e?.status===401){setStatus('Reconnect Google','Google authorization expired. Local progress is safe.',{lastError:e.message||String(e)});return;}const suffix=e?.status===403?` Google returned 403${e.reason?` (${e.reason})`:''}.`:'';setStatus('Backup failed — local progress is safe',(e.message||String(e))+suffix,{lastError:e.message||String(e)});}
  function installStyles(){
    if(document.getElementById('stepProgressSyncTestStyle'))return;const st=document.createElement('style');st.id='stepProgressSyncTestStyle';st.textContent=`
    #stepProgressTestBadge{position:fixed;right:10px;bottom:10px;z-index:99999;background:#7f1d1d;color:#fff;border:1px solid #450a0a;border-radius:999px;padding:5px 9px;font:800 10px/1.2 Arial,sans-serif;pointer-events:none;opacity:.88;letter-spacing:.04em}
    #progressSyncTab{position:relative}#progressSyncTab .sync-tab-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-left:7px;background:#7d92a2;box-shadow:0 0 0 3px rgba(125,146,162,.14)}#progressSyncTab.sync-connected .sync-tab-dot{background:#34c78b;box-shadow:0 0 0 3px rgba(52,199,139,.16)}#progressSyncTab.sync-attention .sync-tab-dot{background:#f0ad45;box-shadow:0 0 0 3px rgba(240,173,69,.16)}
    #progressSyncPanel{--sync-ink:#0b1f2d;--sync-muted:#637888;--sync-line:#dbe6ed;--sync-soft:#f5f9fb;--sync-green:#159468;--sync-warn:#b87312;--sync-red:#a83b3b}#progressSyncPanel .sync-hero{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:22px 24px;margin-bottom:18px}#progressSyncPanel .sync-hero h2{margin:2px 0 5px;color:var(--sync-ink);font-size:25px}#progressSyncPanel .sync-hero p{margin:0;color:var(--sync-muted);font-size:13px;max-width:760px;line-height:1.55}
    #progressSyncPanel .sync-status-pill{display:inline-flex;align-items:center;gap:8px;white-space:nowrap;border:1px solid var(--sync-line);background:#fff;border-radius:999px;padding:8px 12px;font-size:12px;font-weight:900;color:var(--sync-ink)}#progressSyncPanel .sync-status-pill i{width:9px;height:9px;border-radius:50%;background:#899ba8;display:block}#progressSyncPanel .sync-status-pill.good i{background:var(--sync-green)}#progressSyncPanel .sync-status-pill.warn i{background:#e2a032}#progressSyncPanel .sync-status-pill.bad i{background:var(--sync-red)}#progressSyncPanel .sync-status-pill.busy i{background:#1976d2;animation:stepSyncPulse 1s infinite alternate}@keyframes stepSyncPulse{from{opacity:.35}to{opacity:1}}
    #progressSyncPanel .sync-layout{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:18px}#progressSyncPanel .sync-card{background:#fff;border:1px solid var(--sync-line);border-radius:22px;padding:20px;box-shadow:0 12px 30px rgba(24,54,84,.07)}#progressSyncPanel .sync-card h3{margin:0 0 5px;color:var(--sync-ink);font-size:16px}#progressSyncPanel .sync-card>p{margin:0;color:var(--sync-muted);font-size:12px;line-height:1.5}
    #progressSyncPanel .sync-account{display:flex;align-items:center;gap:14px;margin-top:18px;padding:15px;border:1px solid #d7ebe3;background:#f5fbf8;border-radius:18px}#progressSyncPanel .sync-avatar{width:42px;height:42px;flex:0 0 42px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#153b54;color:#fff;font-size:16px;font-weight:950}#progressSyncPanel .sync-account-email{font-size:14px;font-weight:900;color:var(--sync-ink)}#progressSyncPanel .sync-account-sub{font-size:11px;color:var(--sync-muted);margin-top:3px}#progressSyncPanel .sync-disconnected{margin-top:18px;padding:18px;border:1px dashed #cbdbe5;background:var(--sync-soft);border-radius:18px;font-size:12px;color:var(--sync-muted)}
    #progressSyncPanel .sync-detail{margin-top:13px;border-radius:14px;padding:11px 13px;background:var(--sync-soft);color:#425c6d;font-size:12px;line-height:1.5;min-height:18px}#progressSyncPanel .sync-detail.bad{background:#fff5f5;color:#883838;border:1px solid #f0d4d4}#progressSyncPanel .sync-detail.warn{background:#fff9ed;color:#7f5a16;border:1px solid #f0dfb8}#progressSyncPanel .sync-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:15px}#progressSyncPanel .sync-actions button{min-width:128px}
    #progressSyncPanel .sync-meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}#progressSyncPanel .sync-meta{background:var(--sync-soft);border:1px solid #e3edf2;border-radius:14px;padding:11px}#progressSyncPanel .sync-meta span{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.055em;font-weight:900;color:#79909f}#progressSyncPanel .sync-meta b{display:block;margin-top:4px;font-size:12px;color:var(--sync-ink);word-break:break-word}
    #progressSyncPanel .sync-protection-list{display:flex;flex-direction:column;gap:10px;margin-top:17px}#progressSyncPanel .sync-protection{display:grid;grid-template-columns:31px 1fr;gap:10px;align-items:start;padding:11px;border:1px solid #e2ebf0;border-radius:15px;background:#fbfdfe}#progressSyncPanel .sync-protection-icon{width:31px;height:31px;border-radius:10px;background:#eaf3f8;color:#1f607e;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:950}#progressSyncPanel .sync-protection b{display:block;font-size:12px;color:var(--sync-ink)}#progressSyncPanel .sync-protection span{display:block;font-size:11px;color:var(--sync-muted);margin-top:2px;line-height:1.4}
    #progressSyncPanel .sync-inventory{grid-column:1/-1}#stepSyncInventory{margin-top:14px;display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:9px}#stepSyncInventory .sync-metric{background:var(--sync-soft);border:1px solid #e0ebf1;border-radius:14px;padding:11px}#stepSyncInventory .sync-metric span{display:block;font-size:10px;text-transform:uppercase;color:#78909e;font-weight:850}#stepSyncInventory .sync-metric b{display:block;margin-top:4px;font-size:18px;color:var(--sync-ink)}#progressSyncPanel .sync-footer{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:14px;color:#728797;font-size:11px;flex-wrap:wrap}#progressSyncPanel .sync-footer a{font-weight:850;color:#315f7d;text-decoration:none}.sync-danger{border-color:#e0b8b8!important;color:#8c3030!important}
    @media(max-width:900px){#progressSyncPanel .sync-layout{grid-template-columns:1fr}#progressSyncPanel .sync-hero{flex-direction:column}}@media(max-width:600px){#progressSyncPanel .sync-hero,#progressSyncPanel .sync-card{padding:16px}#progressSyncPanel .sync-meta-grid{grid-template-columns:1fr}#progressSyncPanel .sync-actions button{flex:1 1 140px}}
    `;document.head.appendChild(st);if(!document.getElementById('stepProgressTestBadge')){const badge=document.createElement('div');badge.id='stepProgressTestBadge';badge.textContent='BACKUP TEST • step-simulator-progress';document.body.appendChild(badge);}
  }
  function tone(){if(uiState.status==='Backed up')return'good';if(/Backing up|Connecting/.test(uiState.status))return'busy';if(/pending|available|decision|required|Reconnect|Offline/i.test(uiState.status))return'warn';if(/failed/i.test(uiState.status))return'bad';return'';}
  function connected(){return!!uiState.account&&uiState.status!=='Disconnected'&&uiState.status!=='Reconnect Google';}
  function controls(){if(/Backing up|Connecting/.test(uiState.status))return`<button class="primary" disabled>${uiState.status}</button>`;if(uiState.status==='Reconnect Google')return`<button class="primary" data-step-sync-action="check">Reconnect Google</button><button class="secondary" data-step-sync-action="disconnect">Disconnect</button>`;if(connected()){const force=decisionKeys.length?`<button class="secondary sync-danger" data-step-sync-action="force">Replace Cloud with This Device</button>`:'';return`<button class="primary" data-step-sync-action="backup">Back Up Now</button><button class="secondary" data-step-sync-action="restore-cloud">Restore from Cloud</button>${force}<button class="secondary" data-step-sync-action="disconnect">Disconnect</button>`;}return`<button class="primary" data-step-sync-action="connect">Connect Google Account</button>`;}
  function ensureSurface(){
    const side=document.querySelector('.modern-sidebar');if(side&&!document.getElementById('progressSyncTab')){const btn=document.createElement('button');btn.type='button';btn.id='progressSyncTab';btn.className='menu-tab';btn.innerHTML='Progress Backup <span class="sync-tab-dot" aria-hidden="true"></span>';const settings=document.getElementById('settingsTab');settings?side.insertBefore(btn,settings):side.appendChild(btn);}
    const main=document.querySelector('.modern-main'),settingsPanel=document.getElementById('settingsPanel');if(main&&!document.getElementById('progressSyncPanel')){const p=document.createElement('section');p.id='progressSyncPanel';p.className='mode-panel';p.innerHTML=`
      <div class="sync-hero glass-panel"><div><div class="panel-kicker">Local-first recovery • isolated test</div><h2>Google Progress Backup</h2><p>Each form has its own hidden Drive backup file. The tiny manifest is checked first. Routine answers/highlights stay local; major checkpoints upload only changed form backups when the cloud lineage is safe.</p></div><div id="stepSyncStatusPill" class="sync-status-pill"><i></i><span id="stepSyncStatusText">Disconnected</span></div></div>
      <div class="sync-layout"><section class="sync-card"><h3>Connection & backup</h3><p>Local IndexedDB is always the working source of truth. Cloud restore is explicit and never happens silently.</p><div id="stepSyncAccountArea"></div><div id="stepSyncDetailText" class="sync-detail"></div><div id="stepSyncActions" class="sync-actions"></div><div class="sync-meta-grid"><div class="sync-meta"><span>Last successful backup</span><b id="stepSyncLastText">Never</b></div><div class="sync-meta"><span>Cloud index</span><b>${C.MANIFEST_FILE}</b></div></div></section>
      <section class="sync-card"><h3>Protection model</h3><p>No whole-database merge is performed.</p><div class="sync-protection-list"><div class="sync-protection"><div class="sync-protection-icon">L</div><div><b>Local-first</b><span>Answers/highlights save immediately to the simulator's existing IndexedDB format.</span></div></div><div class="sync-protection"><div class="sync-protection-icon">1</div><div><b>One backup per form</b><span>Completing one form updates only that form's cloud backup plus the tiny manifest.</span></div></div><div class="sync-protection"><div class="sync-protection-icon">#</div><div><b>Lineage guard</b><span>If another device changed the same cloud backup, automatic upload stops and asks for direction.</span></div></div><div class="sync-protection"><div class="sync-protection-icon">↶</div><div><b>Explicit restore</b><span>Cloud never silently overwrites local progress. Restore creates a local rollback checkpoint first.</span></div></div><div class="sync-protection"><div class="sync-protection-icon">B</div><div><b>Backup survives local deletion</b><span>Deleting/resetting local progress never automatically deletes its Drive backup.</span></div></div></div></section>
      <section class="sync-card sync-inventory"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h3>Backup inventory</h3><p>Only the manifest is needed to detect discrepancies; form files are downloaded only during Restore.</p></div><div><button class="secondary" data-step-sync-action="check">Check Cloud Manifest</button> <button class="secondary" data-step-sync-action="validate">Validate Local Progress</button> <button class="secondary" data-step-sync-action="restore-checkpoint">Restore Recovery Checkpoint</button></div></div><div id="stepSyncInventory"><div class="sync-metric"><span>Status</span><b>Not checked</b></div></div><div class="sync-footer"><span>TEST BUILD — production exam-simulator2 remains separate.</span><span><a href="./privacy.html" target="_blank" rel="noopener">Privacy Policy</a> · Build ${C.BUILD}</span></div></section></div>`;settingsPanel?.parentNode?settingsPanel.parentNode.insertBefore(p,settingsPanel.nextSibling):main.appendChild(p);}
    renderUi();
  }
  function activate(){ensureSurface();document.querySelectorAll('.mode-panel.active').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.menu-tab.active').forEach(x=>x.classList.remove('active'));document.getElementById('progressSyncPanel')?.classList.add('active');document.getElementById('progressSyncTab')?.classList.add('active');if(connected())checkCloud({interactive:false}).catch(()=>{});}
  function renderUi(){const pill=document.getElementById('stepSyncStatusPill'),st=document.getElementById('stepSyncStatusText'),dt=document.getElementById('stepSyncDetailText'),aa=document.getElementById('stepSyncAccountArea'),acts=document.getElementById('stepSyncActions'),last=document.getElementById('stepSyncLastText'),tab=document.getElementById('progressSyncTab'),inv=document.getElementById('stepSyncInventory');if(pill)pill.className='sync-status-pill '+tone();if(st)st.textContent=uiState.status;if(dt){dt.textContent=uiState.detail||'';dt.className='sync-detail '+(tone()==='bad'?'bad':tone()==='warn'?'warn':'');}if(aa)aa.innerHTML=connected()?`<div class="sync-account"><div class="sync-avatar">G</div><div><div class="sync-account-email">${String(uiState.account).replace(/[&<>]/g,'')}</div><div class="sync-account-sub">Connected • hidden Drive appDataFolder backups</div></div></div>`:`<div class="sync-disconnected">Progress is currently stored locally. Connecting only checks the cloud manifest; it does not automatically overwrite either copy.</div>`;if(acts)acts.innerHTML=controls();if(last)last.textContent=uiState.lastBackup?new Date(uiState.lastBackup).toLocaleString():'Never';if(tab){tab.classList.toggle('sync-connected',connected());tab.classList.toggle('sync-attention',tone()==='warn'||tone()==='bad');}if(inv&&uiState.summary){const s=uiState.summary,items=[['Local backups',s.localCount],['Cloud backups',s.cloudCount],['Local pending',s.pending],['Cloud available',s.cloudNewer+s.cloudOnly],['Need decision',s.conflicts],['Aligned',s.aligned]];inv.innerHTML=items.map(([a,b])=>`<div class="sync-metric"><span>${a}</span><b>${b}</b></div>`).join('');}}
  async function runValidate(){const r=await S.validateLocal(),inv=document.getElementById('stepSyncInventory');if(inv){const items=[['Loaded forms',r.loadedForms],['Progress forms',r.stats.forms],['Attempts',r.stats.attempts],['Answered',r.stats.answered],['Stem highlights',r.stats.stemHighlights],['Explanation highlights',r.stats.expHighlights],['Qbank tests',r.stats.qbankTests],['Backup entities',r.entities],['Est. local payload',(r.estimatedBytes/1024/1024).toFixed(2)+' MB']];inv.innerHTML=items.map(([a,b])=>`<div class="sync-metric"><span>${a}</span><b>${b}</b></div>`).join('');}return r;}
  async function restoreCheckpoint(){const rt=window.StepExamSyncBridge?.runtime?.();if(rt?.examVisible)throw new Error('Leave the active exam before restoring a recovery checkpoint.');if(!confirm('Restore the last local pre-restore recovery checkpoint?'))return;await S.restoreCheckpoint();await markDirtyAll('Recovery checkpoint restored locally');await runValidate();}
  async function action(a){if(a==='connect')return connect();if(a==='check')return checkCloud({interactive:true});if(a==='backup')return backupNow({reason:'Manual Back Up Now',interactive:true});if(a==='force')return forceBackup();if(a==='restore-cloud')return restoreFromCloud();if(a==='disconnect')return disconnect();if(a==='validate')return runValidate();if(a==='restore-checkpoint')return restoreCheckpoint();}
  document.addEventListener('click',e=>{const tab=e.target?.closest?.('#progressSyncTab');if(tab){e.preventDefault();activate();return;}const other=e.target?.closest?.('.menu-tab:not(#progressSyncTab)');if(other)document.getElementById('progressSyncPanel')?.classList.remove('active');const b=e.target?.closest?.('[data-step-sync-action]');if(!b)return;e.preventDefault();b.disabled=true;action(b.dataset.stepSyncAction).catch(err=>alert(err.message||String(err))).finally(()=>{b.disabled=false;});},true);
  window.addEventListener('stepsim:progress-write',e=>{if(window.__STEP_SYNC_APPLYING_REMOTE)return;recordProgressMutation(e.detail).catch(console.warn);});
  window.addEventListener('stepsim:catalog-write',()=>{if(window.__STEP_SYNC_APPLYING_REMOTE)return;markDirtyAll('Catalog/result metadata changed').catch(()=>{});});
  document.addEventListener('click',e=>{const el=e.target?.closest?.('#finishBlock,#endBlockBtn,#backMenu,#reportSaveMenu,#menuNow,[data-v9="delete-attempt"],[data-v9="qbank-delete"]');if(el)R.meta.get('syncEnabled',false).then(on=>{if(on)scheduleCheckpoint(`Major checkpoint: ${el.id||el.dataset?.v9||'navigation'}`,2200);});},true);
  window.addEventListener('online',()=>{R.meta.get('syncEnabled',false).then(on=>{if(on)scheduleCheckpoint('Network restored',1200);});});
  async function boot(){installStyles();document.title='Step Simulator Progress — BACKUP TEST';if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js?v='+encodeURIComponent(C.BUILD),{scope:'./'});}catch(e){console.warn('TEST service worker registration failed',e);}}const mo=new MutationObserver(()=>{if(!document.getElementById('progressSyncTab')||!document.getElementById('progressSyncPanel'))ensureSurface();});mo.observe(document.documentElement,{childList:true,subtree:true});ensureSurface();const enabled=await R.meta.get('syncEnabled',false),acct=await R.meta.get('googleAccount',null),last=await R.meta.get('lastBackupAt','');uiState.account=acct?.email||'';uiState.lastBackup=last||'';if(enabled){if(A.getState().authorized){setStatus('Local backup pending','Checking the tiny cloud manifest after app open…');setTimeout(()=>backupNow({reason:'App startup checkpoint',interactive:false}).catch(()=>{}),1200);}else setStatus('Reconnect Google','Google backup is enabled, but this browser session needs authorization again.');}else setStatus('Disconnected','Progress is currently stored locally in this isolated TEST build.');}
  R.sync={backupNow,checkCloud,restoreFromCloud,connect,disconnect,markDirtyKey,getState:()=>({...uiState}),runValidate};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
